### ISSUE TITLE
Text output should use outward rounding

### ISSUE THREAD

**Issue by oheim** [benEnsta/pyIbex#10]
```
>>> pyIbex.exp(Interval(1))
[2.71828, 2.71828]
```

As you can see in above example, the actual result is not contained in the interval described by the text output (better: `[2.7182, 2.7183]`). Another similar example:

```
>>> pyIbex.Interval(1 + math.pow(2, -52))
[1, 1]
```

(should be `[1, 1.0001]`)

**Comment by ThomasLeMezo** [comment]
The matter is that python doesn't show all the digits. If you print the lower and upper bound of your interval, you should have correct values
```
>>> c = pyIbex.exp(Interval(1))
>>> Interval.lb(c)
2.7182818284590433
>>> Interval.ub(c)
2.718281828459048
```

**Comment by oheim** [comment]
Yes, as you can see, the interval boundaries cover a different interval than is written in the console. In these examples the intervals are disjoint, but should be subsets. Another example:
````
>>> 2 * pyIbex.asin(Interval(0, 1))
[0, 3.14159]
````
The interval covers π internally, which is good, but the output suggests that π is not contained in the interval.

**Comment by benEnsta** [comment]
Thanks for reporting the issue. 
I will work on that.

**Comment by benEnsta** [comment]
The method __str__ and __repr__ can be overloaded to show more digits.
For instance with
```python
def myPrint(itv):
    return "[%3.16f, %3.16f]" % (itv.lb(), itv.ub())
Interval.__str__ = myPrint

print(Interval(2.3442, 21.3212) )
>>> [2.3441999999999998, 21.3212000000000010]
```
