### ISSUE TITLE
Several arithmetic errors

### ISSUE THREAD

**Issue by oheim** [benEnsta/pyIbex#11]
The following errors have been found using pyIbex 1.1.3 and are probably derived from IBEX.
1. Interval.ALL_REALS.contains(∞) should be false, because an interval is a subset of the reals and ∞ is no real number (same is true for -∞).
2. pyIbex.atan2([0, 0], [entire]) should contain [0, π], but is [empty].
3. pyIbex.atan2([-2, -0.1], [entire]) should contain [-π, 0], but is [empty].
4. pyIbex.atan2([-2, 0], [entire]) should contain [-π, π], but is [empty].
5. pyIbex.atan2([-2, 0], [-2, 1]) should contain [-π, π], but is [-π, 0].
6. pyIbex.atan2([0, 1], [entire]) should contain [0, π], but is [empty].
7. pyIbex.atan2([0.1, 1], [entire]) should contain [0, π], but is [empty].
8. pyIbex.atanh([1, ∞]) and pyIbex.atanh([1, 1]) return [+∞], which is not an interval, should be [empty].
9. pyIbex.atanh([-∞, -1]) and pyIbex.atanh([-1, -1]) return [-∞], which is not an interval, should be [empty].
10. `pyIbex.sin(Interval(float.fromhex('-0X1.921FB54442D18P+1'), 0.0))` does not cover 0 as a possible result.
11. pyIbex.bwd_abs([-1.9, 0.2], [-0.2, 0.2]) increases the size of x, which should never happen for backward arithmetics.
12. pyIbex.bwd_pow([-1, 5], 0, [-51, 12]) reduces the size of x, which is wrong.
13. pyIbex.bwd_pow([1, 1], 0, [entire]) should produce x = [entire], but is x = [-1, 1].

The following cases of poor accuracy could be improved:
1. pow([empty], 0) returns [1, 1], should be [empty].
2. pyIbex.sqrt([entire]), pyIbex.sqrt([0, 1]) and other values for x produce a negative lower boundary, should be zero.
3. `pyIbex.tan(Interval(0.0, float.fromhex('0X1.921FB54442D18P+0')))` returns [entire], should be [0, 1.63312e+16].
4. `pyIbex.bwd_abs(Interval(float.fromhex('-0x1p-1022'), float.fromhex('-0x1p-1022')), Interval.ALL_REALS)` should produce x = [empty]. **Also this function call modifies the content of Interval.ALL_REALS, which is bad.**
5. pyIbex.bwd_abs([-1, 0], [entire]) should produce x = [0, 0], but is [-1, 1].
6. pyIbex.bwd_abs([-∞, 0], [entire]) should produce x = [0, 0], but is [entire].
7. pyIbex.bwd_abs([-∞, -1], [entire]) should produce x = [empty], but is [entire].
8. pyIbex.bwd_abs([-∞, 1], [entire]) should produce x = [-1, 1], but is [entire].
9. Interval(float.fromhex('-0X0.0000000000002P-1022'), float.fromhex('0X0.0000000000001P-1022')).mid() should use IEEE 754 rounding mode “to nearest, ties to even” and produce 0.
10. pyIbex.bwd_cosh([empty], [0, ∞]) should produce x = [empty], but is x = [0, ∞].
11. pyIbex.bwd_cosh([empty], [entire]) should produce x = [empty], but is x = [entire].
12. pyIbex.bwd_pow([-1, 0], 0, [-1, 1]) should produce x = [empty], but is x = [-1, 1].
13. pyIbex.bwd_pow([0, 0], -1, [-5.1, 55.5]) should produce x = [empty], but is x = [0, 0].
14. pyIbex.bwd_pow([-∞, 0], -3, [5.1, 55.5]) should produce x = [empty], but is x = [5.1, 55.5].
15. pyIbex.bwd_pow([0, ∞], 3, [entire]) should not produce a negative lower boundary.
16. pyIbex.bwd_pow([-∞, 0], 3, [entire]) should not produce a positive upper boundary.
17. pyIbex.bwd_pow([-10, 0], -2, [entire]) should produce x = [empty], but is x = [entire].
18. pyIbex.bwd_pow([-∞, 0], -7, [entire]) should produce x = [-∞, 0], but is [entire].

**Comment by msis** [comment]
Thanks @oheim !
pyIbex now relies on [ibex-lib](https://github.com/ibex-team/ibex-lib/) for the arithmetics, (technically, pyIbex is just a wrapping for now).
Here are some the unitary tests performed for that library that we use : https://github.com/ibex-team/ibex-lib/blob/master/tests/TestArith.cpp 
We will have a look and report the issue to the ibex-team.

**Comment by oheim** [comment]
Thanks for pointing me to your test cases. I have identified above errors with the test suite [[1]](https://sourceforge.net/p/octave/interval/ci/default/tree/test/) and the generator [[2]](https://github.com/oheim/ITF1788), which can produce unit tests for pyIbex.

However, since pyIbex does not produce correctly-rounded (tight) results, many of my test cases are not usable on pyIbex right now.
