### ISSUE TITLE
[install] linux "make install"

### ISSUE THREAD

**Issue by ThomasLeMezo** [benEnsta/pyIbex#5]
Error when execute  `make install`command (for boost & pyibex)
```
make install
[  5%] Built target prim
[100%] Built target ibex
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/include/ieee
CMake Error at 3rd/filibsrc/cmake_install.cmake:36 (FILE):
  file INSTALL cannot set permissions on "/usr/local/include/ieee"
Call Stack (most recent call first):
  cmake_install.cmake:37 (INCLUDE)`
```
Solved with sudo right?

**Comment by nicolaje** [comment]
Solved with sudo, yes.
If you want to avoid sudo, I guess you could issue : 
cmake -DCMAKE_PREFIX_INSTALL=/Path/To/Somewhere ...
at configuration, where /Path/To/Somewhere doesn't require sudo
You would have to manually tell python where to find the binaries though
