### ISSUE TITLE
Can't pip install

### ISSUE THREAD

**Issue by dpsanders** [benEnsta/pyIbex#8]
```
16:44 $ pip install pyIbex
Collecting pyIbex
  Could not find a version that satisfies the requirement pyIbex (from versions: )
No matching distribution found for pyIbex
```
Tried with Python 2.7, Python 3.4, Pyzo, Anaconda...

**Comment by dpsanders** [comment]
On OSX 10.11.1

**Comment by benEnsta** [comment]
OK thanks for reporting the issue.
The OS version is part of the pip package name. I only build and try the package with my mac on OSX 10.10.
You could try this :
 - download the pip package from [pyIbex-1.1.4-cp34-cp34m-macosx_10_6_intel.whl](https://pypi.python.org/packages/3.4/p/pyIbex/pyIbex-1.1.4-cp34-cp34m-macosx_10_6_intel.whl#md5=06875d0024b722d8459ff7675a7ddc98)
 - change macosx_10_6_intel into macosx_10_11_intel in the file name.

To test use : 
```
pip install ${path_to_your_wheel}
```
Let me know if it works.

**Comment by dpsanders** [comment]
Not quite sure what syntax you meant.
I get the following

```
18:28 $ pip3 install pyIbex-1.1.4-cp34-cp34m-macosx_10_11_intel.whl 
pyIbex-1.1.4-cp34-cp34m-macosx_10_11_intel.whl is not a supported wheel on this platform.
```

**Comment by benEnsta** [comment]
Sorry, I am not an expert with pip 
I added a pip package build with pyzo2015a for mac os X ( again build with my mac on OSX 10.10)
The generated name was : pyIbex-1.1.4-cp34-cp34m-macosx_10_5_x86_64.whl
You can try again the pip install or change *intel.whl into x86_64.whl
The last solution is to build the module from source. Instructions are in the readme.

**Comment by dpsanders** [comment]
The latest pip version now works with Python 3.4 (though, apparently, not with Python 3.5).
Many thanks!
