### ISSUE TITLE
libboost_python-py34.so.1.55.0 not found

### ISSUE THREAD

**Issue by oheim** [benEnsta/pyIbex#9]
Unfortunately, I cannot pip install on GNU/Linux, so I am using the .whl for Version 1.1.3 from IAMOOC for installation.

I get the following error message at runtime when using pyIbex for the first time, see https://travis-ci.org/oheim/ITF1788/builds/91987788#L385
````
ImportError: libboost_python-py34.so.1.55.0: cannot open shared object file: No such file or directory
````

The whole thing happens at Travis-CI, so this should be an Ubuntu 12.04 LTS with Python 3.4. Why is the boost library not found?

**Comment by oheim** [comment]
I have figured out that package `libboost-python1.55.0` from `ppa:boost-latest/ppa` is for python 3.2 only. Do you know any ppas for python 3.4? Building boost from source is not an option in the Travis build script.

**Comment by benEnsta** [comment]
I agree with you and that is why boost-python need to be recompiled.
For the moment I don't have ppa for boost. However, with ubuntu 14.04, the libboost-python1.55 package has been compiled with python 3.4. Maybe travis will update its database in the future.

**Comment by oheim** [comment]
Thanks for the hint. I could download the package from http://packages.ubuntu.com/vivid/libboost-python1.55.0 and successfully `dpkg -i`

**Comment by eudoxos** [comment]
@oheim: would you mind sharing some details? Did you have to download all the rest of boost? Or you only got that binary from vivid and compiled using headers from trusty? I am facing the same problem in a different project.

**Comment by benEnsta** [comment]
Normally libboost-python1.55-dev includes headers and libs but not the rest of boost.
If you want to avoid boost dependancies, take a look at [pybind11](https://github.com/wjakob/pybind11).
I will use it instead of boost-python in the next version of this project.

**Comment by oheim** [comment]
@eudoxos, here is what I did to get pyIbex running on Travis CI:
https://github.com/oheim/ITF1788/commit/18a193d935448d0734745cd09ab5f75269ace1a2

I was happy when I finally had it up and running and didn't dare to touch it since then ;-)

**Comment by eudoxos** [comment]
Thanks for links :)
